const express=require("express")
const authentication=require("../../middleware/authentication")
const StoreProductDetailsController = require("../../controllers/platform_store/store_product_details.controller")
const router=express.Router()
router.use(authentication)
router.get("/",StoreProductDetailsController.all_store_product_details)
router.post("/",StoreProductDetailsController.create_store_product_details)
router.get("/:id",StoreProductDetailsController.single_store_product_details)
router.patch("/:id",StoreProductDetailsController.update_store_product_details)
router.delete("/:id",StoreProductDetailsController.delete_store_product_details)