import {
    Apps,
    BakeryDining,
    BookTwoTone,
    CurtainsTwoTone,
    DesignServicesRounded,
    Diversity2,
    ElectricMeter,
    HealthAndSafetyTwoTone,
    HelpCenter,
    HomeRepairService,
    LocalAtmRounded,
    LocalGroceryStore,
    MedicalInformation,
    Mosque,
    Newspaper,
    Store,
    TodaySharp,
    VolumeDownOutlined,
    WaterDropSharp,
    WorkRounded,
  } from "@mui/icons-material";
const size="large"
  export const front_shopes = [
    {
      id: 1,
      name: "app store",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <Apps  fontSize={size} />,
      path: "/app_store",
    },
    {
      id: 2,
      name: "art store",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <DesignServicesRounded  fontSize={size}/>,
      path: "/art_store",
    },
    {
      id: 3,
      name: "book store",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <BookTwoTone  fontSize={size}/>,
      path: "/book_store",
    },
    {
      id: 4,
      name: "cloth store",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <Store  fontSize={size}/>,
      path: "/cloth_store",
    },
    {
      id: 5,
      name: "donation",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <Mosque  fontSize={size}/>,
      path: "/donation_center",
    },
    {
      id: 6,
      name: "elc store",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <ElectricMeter  fontSize={size}/>,
      path: "/elc_store",
    },
    {
      id: 7,
      name: "grocary store",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <LocalGroceryStore  fontSize={size}/>,
      path: "/grocary_store",
    },
    {
      id: 8,
      name: "home service",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <HomeRepairService  fontSize={size}/>,
      path: "/home_service",
    },
    {
      id: 9,
      name: "hire me",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <WorkRounded  fontSize={size}/>,
      path: "/job_site",
    },
    {
      id: 10,
      name: "pharmacy store",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <MedicalInformation  fontSize={size}/>,
      path: "/pharmacy_store",
    },
    {
      id: 11,
      name: "meet doctor",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <HealthAndSafetyTwoTone  fontSize={size}/>,
      path: "/meet_doctor",
    },
    {
      id: 12,
      name: "Food Store",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <BakeryDining  fontSize={size}/>,
      path: "/money_bank",
    },
    {
      id: 12,
      name: "money bank",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <LocalAtmRounded  fontSize={size}/>,
      path: "/money_bank",
    },
    {
      id: 14,
      name: "one demand store",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <CurtainsTwoTone  fontSize={size}/>,
      path: "/one_demand_store",
    },
    {
      id: 15,
      name: "Regular Shop",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <TodaySharp  fontSize={size}/>,
      path: "/regular_shop",
    },
    {
      id: 16,
      name: "perfume store",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <WaterDropSharp  fontSize={size}/>,
      path: "/perfume_store",
    },
    {
      id: 17,
      name: "Qurans",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <VolumeDownOutlined  fontSize={size}/>,
      path: "/qurans",
    },
    {
      id: 18,
      name: "Social network",
      icon: "",
      onClick: (e) => {return e},
      left_icon: <Diversity2  fontSize={size}/>,
      path: "/social_network",
    },
  ];
  