import {
  Apps,
  BakeryDining,
  BookTwoTone,
  CurtainsTwoTone,
  DesignServicesRounded,
  Diversity2,
  ElectricMeter,
  HealthAndSafetyTwoTone,
  HelpCenter,
  HomeRepairService,
  LocalAtmRounded,
  LocalGroceryStore,
  MedicalInformation,
  Mosque,
  Newspaper,
  Payment,
  Store,
  TodaySharp,
  VolumeDownOutlined,
  WaterDropSharp,
  WorkRounded,
} from "@mui/icons-material";
export const shopes = [
  {
    id: 1,
    name: "app store management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <Apps fontSize="small" />,
    path: "/app_store",
  },
  {
    id: 2,
    name: "art store management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <DesignServicesRounded fontSize="small" />,
    path: "/art_store",
  },
  {
    id: 3,
    name: "book store management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <BookTwoTone fontSize="small" />,
    path: "/book_store",
  },
  {
    id: 4,
    name: "cloth store management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <Store fontSize="small" />,
    path: "/cloth_store",
  },
  {
    id: 5,
    name: "donation management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <Mosque fontSize="small" />,
    path: "/donation_center",
  },
  {
    id: 6,
    name: "elc store management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <ElectricMeter fontSize="small" />,
    path: "/elc_store",
  },
  {
    id: 7,
    name: "grocary store management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <LocalGroceryStore fontSize="small" />,
    path: "/grocary_store",
  },
  {
    id: 8,
    name: "home service management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <HomeRepairService fontSize="small" />,
    path: "/home_service",
  },
  {
    id: 9,
    name: "hire me management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <WorkRounded fontSize="small" />,
    path: "/job_site",
  },
  {
    id: 10,
    name: "pharmacy store management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <MedicalInformation fontSize="small" />,
    path: "/pharmacy_store",
  },
  {
    id: 11,
    name: "meet doctor management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <HealthAndSafetyTwoTone fontSize="small" />,
    path: "/meet_doctor",
  },
  {
    id: 12,
    name: "Food Store management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <BakeryDining fontSize="small" />,
    path: "/money_bank",
  },
  {
    id: 12,
    name: "money bank management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <LocalAtmRounded fontSize="small" />,
    path: "/money_bank",
  },
  {
    id: 14,
    name: "one demand store management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <CurtainsTwoTone fontSize="small" />,
    path: "/one_demand_store",
  },
  {
    id: 15,
    name: "Regular Shop management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <TodaySharp fontSize="small" />,
    path: "/regular_shop",
  },
  {
    id: 16,
    name: "perfume store management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <WaterDropSharp fontSize="small" />,
    path: "/perfume_store",
  },
  {
    id: 17,
    name: "Qurans management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <VolumeDownOutlined fontSize="small" />,
    path: "/qurans",
  },
  {
    id: 18,
    name: "Social network management",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <Diversity2 fontSize="small" />,
    path: "/social_network",
  },
];
