import {
  Apps,
  BakeryDining,
  BookTwoTone,
  CurtainsTwoTone,
  DesignServicesRounded,
  Diversity2,
  ElectricMeter,
  LocalGroceryStore,
  MedicalInformation,
  Newspaper,
  Store,
  WaterDropSharp,
  WorkRounded,
} from "@mui/icons-material";
export const vendro_shopes = [
  {
    id: 1,
    name: "app store",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <Apps fontSize="small" />,
    path: "/app_store",
  },
  {
    id: 2,
    name: "art store",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <DesignServicesRounded fontSize="small" />,
    path: "/art_store",
  },
  {
    id: 3,
    name: "book store",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <BookTwoTone fontSize="small" />,
    path: "/book_store",
  },
  {
    id: 4,
    name: "cloth store",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <Store fontSize="small" />,
    path: "/cloth_store",
  },
  {
    id: 6,
    name: "electronic store",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <ElectricMeter fontSize="small" />,
    path: "/elc_store",
  },
  {
    id: 7,
    name: "grocary store",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <LocalGroceryStore fontSize="small" />,
    path: "/grocary_store",
  },
  {
    id: 9,
    name: "hire me",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <WorkRounded fontSize="small" />,
    path: "/job_site",
  },
  {
    id: 10,
    name: "pharmacy store",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <MedicalInformation fontSize="small" />,
    path: "/pharmacy_store",
  },
  {
    id: 12,
    name: "Food Store",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <BakeryDining fontSize="small" />,
    path: "/money_bank",
  },
  {
    id: 14,
    name: "one demand store",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <CurtainsTwoTone fontSize="small" />,
    path: "/one_demand_store",
  },
  {
    id: 16,
    name: "perfume store",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <WaterDropSharp fontSize="small" />,
    path: "/perfume_store",
  },
  {
    id: 18,
    name: "Social network",
    icon: "",
    onClick: (e) => {return e},
    left_icon: <Diversity2 fontSize="small" />,
    path: "/social_network",
  },
];
